# Site settings
title: Neato Street View
tagline: Computational Robotics Final Project Fall 2015 - Creating Google Street View for inside Olin buildings
email: shivali.chandra@students.olin.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/neato_street_view" # the subpath of your site, e.g. /blog/
url: "http://skchandra.github.io/neato_street_view/" # the base hostname & protocol for your site
github_username:  skchandra
highlighter: pygments
github: [Repository metadata]

# Build settings
markdown: kramdown
